export const SET_USER = 'setUser'
export const RESET_USER = 'resetUser'
export const REFRESH_TOKEN = 'refreshToken'
export const SET_CAR = 'setCar'
export const SET_DEFECT_ACT = 'setDefectAct'
export const SET_DEFECT_TYPES = 'setDefectTypes'
export const SET_EQUIPMENT = 'setEquipment'
export const SET_PERMISSIONS = 'setPermissions'